defaults:
  - _self_
  - model: default
  - training: base

# Logging config
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: default
  # Override launcher for parallel experiments
  - override hydra/launcher: joblib

# Random seed
seed: 0
embedding: FRQI
# embedding: FRQI, NEQR, ZZFeatureMap

dataset:
  name: mnist
  num_classes: 2


# Extra configuration for logging
hydra:
  searchpath:
    - file://conf/hydra/job_logging/
  launcher:
    n_jobs: 1 # -1 to use all CPU cores
