defaults:
  - _self_
  - dataset: mnist
  - embedding: FRQI
# embedding: FRQI, NEQR, OQIM, NAQSS, ZZFeatureMap, AngleEncoding, RMP
# Logging config
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: default
  # Override launcher for parallel experiments
  - override hydra/launcher: joblib

# Random seed
seed: 0


# Image preprocessing technique for the PxE analysis, used as input for all embedings for the evaluation
image_preprocessing: None
# None, GaussianBlur, ContrastScaling

training:
  epochs: 1
  batch_size: 100
  image_width: 32 # Number of pixels on one side of the square image
  lr: 0.05

model:
  num_layers: 3

# Extra configuration for logging
hydra:
  searchpath:
    - file://conf/hydra/job_logging/
